get http://localhost:8001/saluda
Accept: application/json

###

post http://localhost:8001/saluda
Content-Type: application/json

{
  "tipo": null,
  "msg": "toledo"
}

###

get http://localhost:8001/api/actores
Accept: application/json

###

get http://localhost:8001/api/actores?mode=long
Accept: application/json

###

get http://localhost:8001/api/actores?page=2&sort=lastName,firstName
Accept: application/json

###
get http://localhost:8001/api/actores/1
Accept: application/json

###
post http://localhost:8001/api/actores
Content-Type: application/json

{
  "actorId": 0,
  "firstName": "pepito",
  "lastName": "GRILLO"
}

###
get http://localhost:8001/api/actores/240
Accept: application/json

###
put http://localhost:8001/api/actores/240
Content-Type: application/json

{
  "actorId": 240,
  "firstName": "PEPITO",
  "lastName": "GRILLO"
}


###
delete http://localhost:8001/api/actores/240

###

get http://localhost:8010/peliculas?mode=short
Accept: application/json

###

get http://localhost:8010/peliculas
Accept: application/json

###

get http://localhost:8001/autoapi
Accept: application/json

###

get http://localhost:8001/autoapi/categories/1
Accept: application/json
###

get http://localhost:8001/autoapi/idiomas
Accept: application/json

###

get http://localhost:8001/cliente/raiz
Accept: application/json

###

get http://localhost:8001/cliente/pelis
Accept: application/json

###

get http://localhost:8001/cliente/pelis/1
Accept: application/json

###

get http://localhost:8080/catalogo
Accept: application/json

###

get http://localhost:8080/demos/api/actores
Accept: application/json

###

get http://localhost:8080/buscar

###

get http://localhost:8001/config

###

get http://localhost:8091/seguro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2MjMzMzUyMDEsImV4cCI6MTYyMzMzNTgwMX0.OiE7OJiP5zHQknU563KKz0J81Z6d4FfaYWSbp7lxBwUD3v76uE7aEN3MmZ3jjEBZltxB6taJ_wz1j4J1dmzG9A

###

get http://localhost:8091/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2MjMzMzUyMDEsImV4cCI6MTYyMzMzNTgwMX0.OiE7OJiP5zHQknU563KKz0J81Z6d4FfaYWSbp7lxBwUD3v76uE7aEN3MmZ3jjEBZltxB6taJ_wz1j4J1dmzG9A

###

post http://localhost:8091/login?name=kk&password=kk

###

post http://localhost:8091/login
Content-Type: application/json

{
  "name": "admin",
  "password": "kk"
}

###

get http://localhost:8001/api/actores
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNaWNyb3NlcnZpY2lvc0pXVCIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpYXQiOjE2MjMzMzUyMDEsImV4cCI6MTYyMzMzNTgwMX0.OiE7OJiP5zHQknU563KKz0J81Z6d4FfaYWSbp7lxBwUD3v76uE7aEN3MmZ3jjEBZltxB6taJ_wz1j4J1dmzG9A
